---

- name: "Docker Installation on Ubuntu"
  hosts: ubuntu
  tasks:
    - name: Update all packages
      apt:
          name: '*'
          update_cache: yes
          state: latest
     
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - ca-certificates 
        - apt-transport-https
        - gnupg
        - lsb-release
        
    - name: Add gpg key
      apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present
    
    - name: Add repository into sources list
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker    
        
    - name: Install docker and docker-compose
      apt:
        name:
          - docker
          - docker-compose
        state: latest
    
    - name: Enable Docker service at startup
      service:
        name: docker
        state: started
        enabled: yes
        
    # - name: Create "docker" group
    #   group:
    #     name: docker
    #     state: present
    
    # - name: Add remote "ubuntu" user to "docker" group
    #   user:
    #     name: "{{ ansible_user }}"
    #     group: docker
    #     append: yes
        